apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-pubsub-servicebus
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString # Used for local dev testing.
      value: "<connection string from step 1>"
    - name: consumerID
      value: "tasks-processor-subscription"
scopes:
  - tasksmanager-backend-api
  - tasksmanager-backend-processor