name: Build and Preview Workshop Docs

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'Makefile'

permissions:
  actions: write          # Required for pr-preview-action
  contents: write         # Required for the checkout action to know to kick off (read) and pr-preview-action (write)
  deployments: write      # Required for pr-preview-action
  id-token: write         # Required for pr-preview-action
  pages: write            # Required for pr-preview-action
  pull-requests: write    # Required for pr-preview-action

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview-docs:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"
      - name: Capture branch and tag
        id: branch_name
        run: |
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build workshop site
        if: " github.event.action != 'closed' "
        run: |
          echo "GIT_PYTHON_REFRESH=quiet"
          make build-docs-website
      - name: Release preview to branch
        if: "! github.event.pull_request.head.repo.fork "
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9 # v1.8.1
        with:
          source-dir: ./dist/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
  publish-preview-docs:
    if: "! github.event.pull_request.head.repo.fork "
    name: Preview
    needs: preview-docs
    uses: ./.github/workflows/publish-docs.yml