name: Release Workshop Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'Makefile'
  workflow_dispatch: {}

permissions:
  contents: write         # Required for checkout and upload-pages-artifact actions
  deployments: write      # Required for deploy-pages action
  id-token: write         # Required for deploy-pages action if using OIDC for authentication
  pages: write            # Required for configure-pages, upload-pages-artifact, and deploy-pages actions

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  release-docs:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"
      - name: Capture branch and tag
        id: branch_name
        run: |
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build workshop site
        run: |
          make build-docs-website
      - name: Release all docs to branch
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          folder: ./dist
          branch: gh-pages
          clean-exclude: |
            pr-preview
            .github
  publish-docs:
    name: Publish
    needs: release-docs
    uses: ./.github/workflows/publish-docs.yml